name: sdk-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.12
      
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests wheel jsonschema wget pyyaml pytest pytest-sugar pytest-html rt-thread-studio
      
      - name: Config Github SSH
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          mkdir -p ~/.ssh/
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 43.139.44.192 >> ~/.ssh/known_hosts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check Script Existence
        id: check_script
        run: |
          if [ -f "$GITHUB_WORKSPACE/scripts/merge_sdk.py" ]; then
            echo "script_exists=true" >> $GITHUB_ENV
          else
            echo "script_exists=false" >> $GITHUB_ENV
          fi
      
      - name: Update-Github-Sdk-Index
        if: ${{ github.repository == 'jianbojason/ruiching-sdk-index' && github.ref == 'refs/heads/main' && github.event_name == 'push' && env.script_exists == 'true' }}
        run: |
          ls -l ${{ github.workspace }}/scripts/ 
          cd ${{ github.workspace }}/scripts
          python merge_sdk.py